[package]
name = "slowpoke-telegram"
version = "0.1.1"
authors = ["Alexander Zaitsev <zamazan4ik@tut.by>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-rt = "1.1.1"
actix-web = "3.1.0"
anyhow = "1.0.38"
bincode = "1.3.1"
chrono = "0.4.19"
log = "0.4.11"
once_cell = "1.5.1"
once-cell-regex = "0.2.0"
pretty_env_logger = "0.4.0"
regex = "1.4.1"
serde = { version = "1.0.119", features = ["derive"] }
serde_json = "1.0.59"
sled = "0.34.6"
sqlx = { version = "0.4.2", features = [ "macros", "runtime-tokio-native-tls", "sqlite" ] }
teloxide = "0.3.4"
tokio = { version = "0.2.22", features = ["rt-threaded", "macros"] }
url = "2.2.0"
nom = "5"

[profile.release]
lto = true
